---
- name: Automate the installation of Kubernetes cluster with Ansible
  hosts: k8s_nodes
  gather_facts: false
  become: true
  roles:
   - k8s_cluster 

- name: Initialize the master node
  hosts: master-node
  roles:
   - master_init
