---
- name: Ping the k8s nodes for testing the connectivity
  ansible.builtin.ping:

- name: Disabling swap on k8s nodes (master and worker)
  shell: |
   swapoff -a
   sed -i "s\/swap.img\#/swap.img\g" /etc/fstab

- name: Create k8s sysctl config
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1

- name: Create k8s modules load
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: Loading kernel modules ovrlay and br_netfilter and apply sysctl config
  shell: |
   modprobe overlay
   modprobe br_netfilter 
   systemctl --system

- name: Remove packages that may conflict with Docker Engine 
  shell: |
   for pkg in docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc; do sudo apt-get remove $pkg; done

- name: Set up Docker's apt repository 
  shell: |
   apt-get update
   apt-get install ca-certificates curl
   install -m 0755 -d /etc/apt/keyrings
   curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
   chmod a+r /etc/apt/keyrings/docker.asc
 
- name: Add the repository to Apt sources
  shell: |
   echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
    $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
   sudo apt-get update

- name: Install containerd
  ansible.builtin.apt:
    name: containerd.io
    state: present
   
- name: Configure SystemGroup to true and change sandbox_image
  shell: |
   containerd config default \
   | sed 's/SystemdCgroup = false/SystemdCgroup = true/' \
   | sed 's|sandbox_image = "registry.k8s.io/pause:3.6"|sandbox_image = "registry.k8s.io/pause:3.9"|' \
   | sudo tee /etc/containerd/config.toml
   systemctl restart containerd


